name: 'cTMS'
description: 'GH Action for SAP BTP Cloud Transport Managemente (cTMS) - CD tooling for the SAP Ecosystem'
inputs:
  TOKEN_SERVICE_URL:
    description: 'Value of URL(UAA section) from the service key of your SAP Cloud Transport Management service instance.'
    required: true
  CLIENT_ID:
    description: 'Value of clientid from the service key of your SAP Cloud Transport Management service instance.'
    required: true
  CLIENT_SECRET:
    description: 'Value of clientsecret (uaa section) from the service key of your SAP Cloud Transport Management service instance.'
    required: true
  CTMS_URL:
    description: 'Value of uri from the service key of your SAP Cloud Transport Management service instance.'
    required: true
  CTMS_NODE_NAME:
    description: 'Name of node where content was put in'
    required: true
  USER_NAME:
    description: 'User displayed in Cloud Transport Management UI. If not given, the authentication user will be shown in Cloud Transport Management UI.'
    required: true
  FILE_PATH:
    description: 'File with application content'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'

author: 'Mauricio Lauffer'
